"""initial_migration

Revision ID: 51d1c06346dc
Revises: 
Create Date: 2025-12-06 02:16:05.621739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d1c06346dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_code', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('law_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('law_id', sa.String(length=50), nullable=False),
    sa.Column('law_mst', sa.String(length=50), nullable=False),
    sa.Column('law_name', sa.String(length=500), nullable=False),
    sa.Column('law_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('proclaimed_date', sa.Date(), nullable=True),
    sa.Column('enforced_date', sa.Date(), nullable=True),
    sa.Column('revision_type', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('law_amendments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('law_id', sa.String(length=50), nullable=False),
    sa.Column('law_name', sa.String(length=500), nullable=False),
    sa.Column('old_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('new_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('change_summary', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['new_snapshot_id'], ['law_snapshots.id'], ),
    sa.ForeignKeyConstraint(['old_snapshot_id'], ['law_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordinances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('enacted_date', sa.Date(), nullable=True),
    sa.Column('enforced_date', sa.Date(), nullable=True),
    sa.Column('revision_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('amendment_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amendment_id', sa.Integer(), nullable=False),
    sa.Column('ordinance_id', sa.Integer(), nullable=False),
    sa.Column('need_revision', sa.Boolean(), nullable=False),
    sa.Column('revision_urgency', sa.String(length=20), nullable=True),
    sa.Column('affected_articles', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['amendment_id'], ['law_amendments.id'], ),
    sa.ForeignKeyConstraint(['ordinance_id'], ['ordinances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordinance_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordinance_id', sa.Integer(), nullable=False),
    sa.Column('article_no', sa.String(length=20), nullable=False),
    sa.Column('paragraph_no', sa.String(length=20), nullable=True),
    sa.Column('item_no', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ordinance_id'], ['ordinances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_laws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordinance_id', sa.Integer(), nullable=False),
    sa.Column('law_id', sa.String(length=50), nullable=False),
    sa.Column('law_type', sa.String(length=20), nullable=False),
    sa.Column('law_name', sa.String(length=500), nullable=False),
    sa.Column('related_articles', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ordinance_id'], ['ordinances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_laws')
    op.drop_table('ordinance_articles')
    op.drop_table('amendment_reviews')
    op.drop_table('ordinances')
    op.drop_table('law_amendments')
    op.drop_table('law_snapshots')
    op.drop_table('departments')
    # ### end Alembic commands ###
